Mixed tutorial
sigasi/sigasi_online_demo pull request #1
Opened 2023-07-03 09:38 UTC by onratr-sigasi

Added folders and files for a hierarchical design items. 
Added steps for going through more TODOs in a mixed project.

2023-07-04 16:12 UTC, bartbrosens commented
Some more ideas:
* step_1: the clocked process is a good place to demonstrate the content assist when inserting a case statement using the enum type signal that yields a skeleton FSM. I would place a TODO comment before the "Quick Outline" TODO, instructing the user to start typing `case` and selecting `Case Statement over sig...`
* at the end of step_1: add instructions to open step_2
* at the end of step_2, instruct to close the preprocessor and open step_3
*

2023-07-04 16:13 UTC, bartbrosens commented on step_4_find_references.vhd
Deleted too much? MAX_COUNT is no longer found in other files

2023-07-04 16:25 UTC, bartbrosens commented on step_6_reporting_issues.vhd
> +-- Also view the components that are instatiated by cmd_gen module and go through the TODOs in those design files.
Is it feasible to go step by step? Instead of recommending to open a bunch of files at once, the journey can be kept going file by file. I think this is easier to follow.

2023-07-04 17:54 UTC, bartbrosens commented on tb/testbench.sv
> +    );
Is it somewhere made clear this is an instantiation of a VHDL entity in the SV testbench?

We could also have the user use content assist to create the instantiation themselves

2023-07-05 18:15 UTC, onratr-sigasi commented on step_4_find_references.vhd
Taken back inside and only removed the magic number rename part.

2023-07-05 18:15 UTC, onratr-sigasi commented on step_6_reporting_issues.vhd
> +-- Also view the components that are instatiated by cmd_gen module and go through the TODOs in those design files.
Done.

2023-07-05 18:15 UTC, onratr-sigasi commented on tb/testbench.sv
> +    );
Done

2023-07-06 09:39 UTC, bartbrosens commented on .settings/com.sigasi.hdt.verilog.linting.prefs
If you want to set all rules at once, you can use `all` instead of repeating for all rule numbers. This will also affect future rules with IDs not yet covered here.

2023-07-06 09:40 UTC, bartbrosens commented on vlog/cmd_fsm.v
> +	//      adds a warning for you Hover over stage5_i and read the warning message.
```suggestion
	//      adds a warning for you.
	//      Hover over stage5_i and read the warning message. 
```

2023-07-11 18:05 UTC, bartbrosens commented on .settings/com.sigasi.hdt.verilog.linting.prefs
@onratr-sigasi should these 2 .prefs files in the .settings/ folder be discarded?

2023-07-11 18:10 UTC, bartbrosens commented
Another suggestion, related to lines 23-27 in step_1:

What about removing the `.project` and `.library_mapping.xml` files from the repository? Then the SiStVSC extension won't start initially. This comment can then explain how to start using the SiStVSC extension using the Command Pallette (now inroduced on line 32) to invoke the `Sigasi:  Add VHDL Support` command.

Then, in the step_2_sv.sv file, we can instruct using the `Sigasi:  Add Verilog/SystemVerilog Support` command.

2023-07-11 18:38 UTC, bartbrosens commented on step_3_find_references.vhd
> +--      Open the file step_4_editor_features.vhd
```suggestion
--      Open the file step_4_editor_features.vhd using the *References View*
```

2023-07-11 18:41 UTC, bartbrosens commented on step_5_warnings.vhd
Can we also draw attention to the dead state warning on line 67 and encourage users to resolve the warning by replacing `null` with an actual transition?

2023-07-11 19:12 UTC, bartbrosens commented on step_6_libraries.vhd
> +--------------------------------------------------------------------------------
Could a detour via Ctrl+Click on the clock_generator be added to demonstrate the ability to navigate to a different file in another library?

2023-07-11 19:13 UTC, bartbrosens commented on vlog/cmd_fsm.v
> +	//      adds a warning for you Hover over stage5_i and read the warning message.
Maybe add that the Quick Fix can be used to suppress the warning

2023-07-11 19:16 UTC, bartbrosens commented on vlog/cmd_fsm.v
> +				//default: c_state  <= S_IDLE;
If this line were near the top of the case statement, another warning would be triggered after uncommenting this line.

2023-07-11 19:19 UTC, bartbrosens commented on vhdl/cnt_ena_ctrl.vhd
> +      --      Remove the extra `=` and note how the Error Marker disappears.
```suggestion
      --      In the lines below, Sigasi Studio reports syntax errors. Indeed, in VHDL
      --      you have to use `=` instead of `==` for *equals*.
      --      Remove the extra `=` and note how the Error Markers disappear.
```

2023-07-11 19:22 UTC, bartbrosens commented on vhdl/cnt_ena_ctrl.vhd
> +	--      Add "rst_n" to the list to immediately fix the issue.
Somehow, ATM this warning doesn't come for me. At first I thought it was because of the error further down, though even after fixing the rising_edge I'm not getting the expected warning...

2023-07-11 19:25 UTC, bartbrosens commented on tb/testbench.sv
> +    //      Observe that the port name of cmd_gen is also changed in the cmd_gen.v.
I found this confusing, then realized it's because of the specific kind of port mapping in line 71. Might need some more explanation?

2023-07-11 19:26 UTC, bartbrosens commented on tb/testbench.sv
> +    //      If you've forgotten what `cmd_type` looks like by now you can go back
We're hardly going back to something here. Should be rephrased IMO

2023-07-11 19:28 UTC, bartbrosens commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
This should also work when starting to type. In Eclipse you then need Crtl+Space but VSC starts suggesting automagically.

2023-07-12 22:46 UTC, tivervac requested changes

2023-07-12 22:46 UTC, tivervac commented on final_step_reporting_issues.vhd
> +-- You are now ready to go and set up a project for your own HDL code.
```suggestion
-- You are now ready to set up a project for your own HDL code.
```

2023-07-12 22:46 UTC, tivervac commented on step_1_welcome.vhd
> +-- TODO "Content Asist"
```suggestion
-- TODO "Content Assist"
```

2023-07-12 22:46 UTC, tivervac commented on step_1_welcome.vhd
> +--      yields a skeleton FSM.
```suggestion
--      Sigasi Studio can help you type VHDL code faster. On the line below,
--      press **Ctrl+Space** and select "case state - Case Statement over..." 
--      to insert a skeleton FSM over `state`.
```

2023-07-12 22:46 UTC, tivervac commented on step_1_welcome.vhd
>  --      If you've forgotten what `data_out` looks like by now you can go back
```suggestion
--      If you've forgotten what `data_out` looks like by now, you can go back
```

2023-07-12 22:46 UTC, tivervac commented on step_1_welcome.vhd
> +--      You can now go ahead and continue from step 2.
```suggestion
--      You can now continue to step 2. 
```

2023-07-12 22:46 UTC, tivervac commented on step_2_sv.sv
> +//      You can now go ahead and continue from step 3.
```suggestion
//      You can now continue to step 3. 
```

2023-07-12 22:46 UTC, tivervac commented on step_2_sv.sv
> +//      Close the preprocessor and open the file step_3_find_references.vhd
```suggestion
//      Close the Preprocessor View and open the file step_3_find_references.vhd  
```

2023-07-12 22:46 UTC, tivervac commented on step_3_find_references.vhd
> +--      You can now go ahead and continue from step 4.
```suggestion
--      You can now continue to step 4. 
```

2023-07-12 22:46 UTC, tivervac commented on step_5_warnings.vhd
> +--      You can now go ahead and continue from step 6.
```suggestion
--      You can now continue to step 6. 
```

2023-07-12 22:46 UTC, tivervac commented on step_6_libraries.vhd
> +--      Open the file cmd_fsm.v in the vlog folder
```suggestion
--      Open the file cmd_fsm.v in the vlog folder.
```

2023-07-12 22:46 UTC, tivervac commented on step_6_libraries.vhd
> +--      Open the file cmd_fsm.v in the vlog folder
You probably want dots in the other next steps as well

2023-07-12 22:46 UTC, tivervac commented on tb/testbench.sv
> +    //      Observe that the port name of cmd_gen is also changed in the cmd_gen.v.
```suggestion
    //      Observe that the port name of `cmd_gen` is also changed in the cmd_gen.v.   
```

2023-07-12 22:46 UTC, tivervac commented on tb/testbench.sv
> +    //      If you've forgotten what `cmd_type` looks like by now you can go back
```suggestion
    //      If you've forgotten what `cmd_type` looks like by now, you can go back
```

2023-07-12 22:46 UTC, tivervac commented on tb/testbench.sv
> +    //      to it using the quick outline. Press **Ctrl+Shift+O** and type "cmd_type".
That's not the VSCode keybind

2023-07-12 22:46 UTC, tivervac commented on vhdl/cnt_ena_ctrl.vhd
> +      -- again and continue with the TODOs below. Notice that this file is located
Incorrect indentation at the start

2023-07-12 22:46 UTC, tivervac commented on vhdl/cnt_ena_ctrl.vhd
> +      --      Notice how the data type, value and comments of this generic shows up in
```suggestion
      --      Notice how the data type, value, and comments of this generic show up in
```

2023-07-12 22:46 UTC, tivervac commented on vlog/cmd_fsm.v
> +				//      Notice how the data type, value and comments of the objects shows up in
```suggestion
				//      Notice how the data type, value, and comments of the objects show up in
```

2023-07-12 22:46 UTC, tivervac commented on vlog/cmd_gen.v
> +	//      In the line below, right click on the word cmd_gen and
```suggestion
	//      In the line below, right-click on the word cmd_gen and 
```

2023-07-12 22:46 UTC, tivervac commented on vlog/cmd_gen.v
> +	//      Note that "Hierarchy View" is now populated and browse the hierarchy there.
```suggestion
	//      Note that "Hierarchy View" is now populated and you can browse the hierarchy there.
```

2023-07-12 22:46 UTC, tivervac commented on vlog/cmd_gen.v
> +	// TODO "Rename"
Broken indentation

2023-07-13 17:46 UTC, onratr-sigasi commented on final_step_reporting_issues.vhd
> +-- You are now ready to go and set up a project for your own HDL code.
Done

2023-07-13 17:46 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +-- TODO "Content Asist"
Done

2023-07-13 17:46 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--      yields a skeleton FSM.
Done

2023-07-13 17:46 UTC, onratr-sigasi commented on step_1_welcome.vhd
>  --      If you've forgotten what `data_out` looks like by now you can go back
Done

2023-07-13 17:46 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--      You can now go ahead and continue from step 2.
Done

2023-07-13 17:46 UTC, onratr-sigasi commented on vhdl/cnt_ena_ctrl.vhd
> +      --      Notice how the data type, value and comments of this generic shows up in
Done

2023-07-13 17:47 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +				//      Notice how the data type, value and comments of the objects shows up in
Done

2023-07-13 17:47 UTC, onratr-sigasi commented on vlog/cmd_gen.v
> +	//      In the line below, right click on the word cmd_gen and
Done

2023-07-13 17:47 UTC, onratr-sigasi commented on vlog/cmd_gen.v
> +	//      Note that "Hierarchy View" is now populated and browse the hierarchy there.
Done

2023-07-13 17:47 UTC, onratr-sigasi commented on vlog/cmd_gen.v
> +	// TODO "Rename"
I didn't see any broken indentation

2023-07-13 17:52 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      Observe that the port name of cmd_gen is also changed in the cmd_gen.v.
Outdated

2023-07-13 17:52 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      If you've forgotten what `cmd_type` looks like by now you can go back
Done

2023-07-13 17:53 UTC, onratr-sigasi commented on vhdl/cnt_ena_ctrl.vhd
> +      -- again and continue with the TODOs below. Notice that this file is located
Outdated

2023-07-13 17:55 UTC, onratr-sigasi commented on step_6_libraries.vhd
> +--      Open the file cmd_fsm.v in the vlog folder
Done - it's sometimes forgotten ;)

2023-07-13 17:56 UTC, onratr-sigasi commented on step_5_warnings.vhd
> +--      You can now go ahead and continue from step 6.
Done

2023-07-13 17:56 UTC, onratr-sigasi commented on step_3_find_references.vhd
> +--      You can now go ahead and continue from step 4.
Done

2023-07-13 17:56 UTC, onratr-sigasi commented on step_2_sv.sv
> +//      Close the preprocessor and open the file step_3_find_references.vhd
Done

2023-07-13 17:56 UTC, onratr-sigasi commented on step_2_sv.sv
> +//      You can now go ahead and continue from step 3.
Done

2023-07-13 17:57 UTC, onratr-sigasi commented on .settings/com.sigasi.hdt.verilog.linting.prefs
Deleted the files.

2023-07-13 17:57 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	//      adds a warning for you Hover over stage5_i and read the warning message.
Done.

2023-07-13 17:57 UTC, onratr-sigasi commented on step_3_find_references.vhd
> +--      Open the file step_4_editor_features.vhd
Done.

2023-07-13 17:58 UTC, onratr-sigasi commented on step_5_warnings.vhd
Done.

2023-07-13 17:59 UTC, onratr-sigasi commented on step_6_libraries.vhd
> +--------------------------------------------------------------------------------
Done.

2023-07-13 18:00 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +				//default: c_state  <= S_IDLE;
Done.

2023-07-13 18:00 UTC, onratr-sigasi commented on vhdl/cnt_ena_ctrl.vhd
> +      --      Remove the extra `=` and note how the Error Marker disappears.
Done.

2023-07-13 18:00 UTC, onratr-sigasi commented on vhdl/cnt_ena_ctrl.vhd
> +	--      Add "rst_n" to the list to immediately fix the issue.
Didn't change anything for this.

2023-07-13 18:00 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      Observe that the port name of cmd_gen is also changed in the cmd_gen.v.
Added explanation.

2023-07-13 18:01 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      If you've forgotten what `cmd_type` looks like by now you can go back
Moved this to where that signals is used.

2023-07-13 18:02 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
Wouldn't it be better if we do it inline with Eclipse version? Because then the user might also expect the same behavior from the Eclipse version.

2023-07-14 09:16 UTC, bartbrosens commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
Sadly it's one of the differences between how Eclipse and VS Code are working. This is a feature request for Eclipse but can't be done atm. In Ecliipse you'll only have automatic suggestions e.g. when working with records and typing the `.`.

2023-07-14 09:19 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
What I meant was, wouldn't it be better if we keep the demo inline with Eclipse capabilities?

2023-07-14 09:59 UTC, bartbrosens commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
No, this is meant for VS Code in the first place.

2023-07-14 10:19 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
Ok

2023-07-14 11:30 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      On the line below, press **Ctrl+Space** and select "clock generator - Instantiate design unit"
Done

2023-07-14 11:30 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      to it using the quick outline. Press **Ctrl+Shift+O** and type "cmd_type".
I checked with @bartbrosens and it's the correct keybind in the online version

2023-07-18 14:52 UTC, tivervac requested changes
In general, it would be good to go over all the TODOs again and apply the markup consistently. The markup I noticed was as follows

* **Keybinds**
* "Files"
* "Quoted Commands"
* 'Quoted Code'
* **Views**

But for example, quoted code sometimes uses backticks, files often have no markup, many identifiers don't use markup etc.

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
>  --       These should be checked into your version control system.
Can't comment on non-edited lines but this seems better

```
-- You made a great choice opening the online version of Sigasi. You are now
-- ready to explore most of the functionalities that are also provided by the
-- Sigasi Studio extension for VS Code.
--
-- This online workspace will live for a limited time only and there is no
-- persistence. You can use the workspace to explore this Sigasi demo project,
-- or you can use git to clone your own project, make changes, and commit your
-- changes before this workspace expires.
--
-- This tutorial project will guide you during your first steps. In a few minutes,
-- you will have learned the basics of how Sigasi helps you work with HDL files.
--
-- Just follow the comments below that are marked 'TODO'.
--------------------------------------------------------------------------------
-- NOTE: You can download extensions that change the keybinds of VSCode to match
--       an editor of your choice such as Eclipse, IntelliJ IDEA, Vim.
--       In this tutorial, we'll use the default VS Code keybindings.
```

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
>  --       When you change project or folder settings these will be saved in
I also note that you try to stay within 80 characters, but many lines are much longer. I suggest using a VS Code ruler to make sure everything is formatted as expected

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +--       Note that, in this project, **.project** and **.library_mapping.xml**
```suggestion
--       Note that, in this project, the **.project** and **.library_mapping.xml**
```

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +-- TODO The Command Palette is your go to for any command you want to execute
```suggestion
-- TODO The Command Palette is your go-to for any command you want to execute
```

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +--      in VSCode. Open it by pressing **Ctrl+Shift+P**, start typing
```suggestion
--      in VS Code. Open it by pressing **Ctrl+Shift+P**, start typing 
```

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +--      This will create **.project** and **.library_mapping.xml** files and start
```suggestion
--      This will create the **.project** and **.library_mapping.xml** files and start 
```

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
>  --      **Shift+Alt+F**.
Keybinds might have to be revisited, I'm testing in VS Code, but they might differ between Linux and Windows as well. Anyhow, on VS Code, formatting is Ctrl+Shift+I

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
>  ------------------------------------------------------------------------------------
I would Ctrl+F for missing oxford commas, e.g., 

`data type, direction and comments` -> `data type, direction, and comments`

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +
`the main process of this architecture` -> `The main process of this architecture`

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
>  --      behind the "ri" press **Ctrl+Space** and select "rising_edge".
There are two though, so slightly confusing :/

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +--      Sigasi Studio can help you type VHDL code faster. On the line below,
First line is a copy paste of the TODO above, no need to repeat. Also, first it's called Autocomplete, here it's called content assist. We should pick one

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +--------------------------------------------------------------------------------
```suggestion
--      Sigasi Studio can help you type VHDL code faster.
--      On the line below, type the letter "c" and select "case state - Case Statement over..." 
--      from the revealed drop-down list to insert a skeleton FSM over "state".
--------------------------------------------------------------------------------
```

2023-07-18 14:52 UTC, tivervac commented on step_1_welcome.vhd
> +--      Open the file step_2_sv.sv
```suggestion
--      Open the file "step_2_sv.sv".
```

2023-07-18 14:52 UTC, tivervac commented on step_2_sv.sv
> +//      This will make the project a mixed language project.
```suggestion
//      This will make the project a mixed-language project.
```

2023-07-18 14:52 UTC, tivervac commented on step_2_sv.sv
>  //      been configured so you're getting an error here. To configure this open the preference page
This would be better

```
// TODO "Setup include path"
//      "included.svh" is located in the "include" folder but the include path has not yet
//      been configured so you're getting an error here. To configure this, open the Preference View
//      by right-clicking your project in the Project View and navigating to "Verilog Preprocessor Settings".
//      There you can add "include" as an include path. Don't forget to press "Apply" in the upper right corner.
```

As well as

```
// TODO "Adjust validation settings"
//      On the line below, you're getting a warning because the module name is different from the filename.
//      If you don't mind this, you can ignore this warning by opening the Preference View and searching for
//      the Verilog validation named "17. File name does not match design unit".
```

And

```
    // TODO "Setup initial defines"
    //      `BUS_WIDTH is a global define but this has not been set up yet. To configure this, open the Preference View and
    //      add "`define BUS_WIDTH 8" as an initial preprocessor definition in the "Verilog Preprocessor Settings".
    //      Confirm by pressing "Apply" in the upper right corner.
```

And
```
// TODO "Open the Preprocessor View"
//      Inspect your entire expanded file by opening the Preprocessor View. Simply right-click anywhere in the editor
//      and click **Show In > Preprocessor**.
```

2023-07-18 14:52 UTC, tivervac commented on step_3_find_references.vhd
> +--      Open the file step_4_editor_features.vhd using the *References View*
```suggestion
--      Open the file "step_4_editor_features.vhd" using the *References View*
```

2023-07-18 14:52 UTC, tivervac commented on step_2_sv.sv
> +//      Close the *Preprocessor View* and open the file step_3_find_references.vhd
```suggestion
//      Close the *Preprocessor View* and open the file "step_3_find_references.vhd".
```

2023-07-18 14:52 UTC, tivervac commented on step_5_warnings.vhd
For step 4, the first todo is a bit sad, it just jumps 3 lines lower, you hardly notice it

2023-07-18 14:52 UTC, tivervac commented on step_6_libraries.vhd
> +	--		file in another library.
Indentation

2023-07-18 14:52 UTC, tivervac commented on step_5_warnings.vhd
> +--      Open the file step_6_libraries.vhd
```suggestion
--      Open the file "step_6_libraries.vhd".
```

2023-07-18 14:52 UTC, tivervac commented on step_6_libraries.vhd
> +--      Sigasi Studio fully supports VHDL's library mechanism. For that it needs
```suggestion
--      Sigasi Studio fully supports VHDL's library mechanism. For that, it needs
```

2023-07-18 14:52 UTC, tivervac commented on step_6_libraries.vhd
>  --      results in an unknown entity in the `clock_inst` instantiation.
Right click -> Right-click

2023-07-18 14:52 UTC, tivervac commented on step_6_libraries.vhd
> +	--      **F12** or **Ctrl+Left Click** it. This takes you to
```suggestion
	--      **F12** or **Ctrl+Left-Click** it. This takes you to
```

2023-07-18 14:52 UTC, tivervac commented on my_lib/clock_generator.vhd
> +--      Open the file cmd_fsm.v in the vlog folder.
```suggestion
--      Open the file "cmd_fsm.v" in the "vlog" folder.
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +	//		`stage4` is missing from the port list.
Indentation seems off for all the TODOs in this file

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +	output stage4;
Trailing whitespace

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +	//		`stage4` is missing from the port list.
```suggestion
	//		`stage4` is missing from the port list above. 
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +	// 	    In the pop-up, click "Quick Fix" and "suppress" the warning message.
```suggestion
	// 	    In the pop-up, click "Quick Fix..." and "suppress" the warning message.
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +	//		";" is missing from the end of the assign statement.
```suggestion
	//		A ";" is missing from the end of the assign statement. 
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +		//      Default clause is missing from the case statement. Sigasi knows this and
```suggestion
		//      A default clause is missing from the case statement. Sigasi knows this and
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +		// 		Uncomment the line where the "default clause" is and notice how
```suggestion
		// 		Uncomment the line containing the "default clause" and notice how 
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +		//		Also notice that a new warning message appears in the next line.
```suggestion
		//		Also notice that a new warning message appears on the next line.
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +		//		Also notice that a new warning message appears in the next line.
It's appearing on the same line though :thinking: Default should be the last element in the case. I would either place it there, or learn the user how to move it wilt alt-down

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_fsm.v
> +//      Open the file cmd_gen.v in the 'vlog' folder.
```suggestion
//      Open the file "cmd_gen.v" in the "vlog" folder.
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_gen.v
> +    //      Notice that two components are instantiated here in this Verilog file.
```suggestion
    //      Notice that two components are instantiated in this file. 
```

2023-07-18 14:52 UTC, tivervac commented on vlog/cmd_gen.v
> +    //      **F12** or **Ctrl+Left Click** it. This takes you to the
```suggestion
    //      **F12** or **Ctrl+Left-Click** it. This takes you to the 
```

2023-07-18 14:52 UTC, tivervac commented on vhdl/cnt_ena_ctrl.vhd
> +--      Open the file testbench.sv in the 'tb' folder.
```suggestion
--      Open the file "testbench.sv" in the "tb" folder.
```

2023-07-18 14:52 UTC, tivervac commented on tb/testbench.sv
> +    //      Observe that the port name of "clk" is also changed in the cmd_gen.v.
```suggestion
    //      Observe that the port name of "clk" is also changed in "cmd_gen.v".  
```

2023-07-18 14:52 UTC, tivervac commented on tb/testbench.sv
> +    //      This is because of the specific kind of port mapping in line 73, where
```suggestion
    //      This is because of the specific kind of port mapping on line 73, where 
```

I have no port mapping on line 73 though :thinking:

2023-07-18 14:52 UTC, tivervac commented on tb/testbench.sv
> +	//      Sigasi can help you search through your projects. To find out
More indentation inconsistencies

2023-07-18 14:52 UTC, tivervac commented on tb/testbench.sv
> +//      Open the file final_step_reporting_issues.vhd
```suggestion
//      Open the file "final_step_reporting_issues.vhd".
```

2023-07-18 14:52 UTC, tivervac commented on final_step_reporting_issues.vhd
>  --
This would be better

```
------------------------------------------------------------------------------------------------------------------------
-- If you got this far, you have learned the basics of working with Sigasi Studio for VS Code.
--
-- Congratulations!
--
-- You are now ready to set up a project for your own HDL code.
------------------------------------------------------------------------------------------------------------------------
-- If you were to encounter any issues, you can contact us at support@sigasi.com
--
-- You can find the Sigasi logs by opening the Log and Tracing Log Views.
-- Open the `Command Palette (Ctrl+Shift+P)` and type `Sigasi: Open Log` or `Sigasi: Open Tracing Log`.
--
-- To increase the logging in the Sigasi log view you can open the `Command Palette (Ctrl+Shift+P)` and type
-- `Sigasi › Server › Log: Level`. `info` is usually enough information for us.
--
-- To see the full tracing logs you should open the settings and set `Sigasi > Trace: Server` to `verbose`.
------------------------------------------------------------------------------------------------------------------------
```

2023-07-18 19:05 UTC, bartbrosens commented on step_1_welcome.vhd
> +--       files are missing. They will be added as you follow the steps.
Like we discussed this afternoon, you can re-add the .project and .library_mapping.xml files and instruct the user to (optionally) remove and re-add these files to see the effect on the extension and to understand what a Sigasi project is about.

2023-07-19 17:42 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +-- TODO The Command Palette is your go to for any command you want to execute
Done.

2023-07-19 17:42 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--      in VSCode. Open it by pressing **Ctrl+Shift+P**, start typing
Done.

2023-07-19 17:46 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +
Done.

2023-07-19 17:49 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--      Sigasi Studio can help you type VHDL code faster. On the line below,
Done.

2023-07-19 17:49 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--------------------------------------------------------------------------------
Done.

2023-07-19 18:09 UTC, onratr-sigasi commented on step_2_sv.sv
>  //      been configured so you're getting an error here. To configure this open the preference page
Done.

2023-07-19 18:11 UTC, onratr-sigasi commented on step_3_find_references.vhd
> +--      Open the file step_4_editor_features.vhd using the *References View*
Done.

2023-07-19 18:11 UTC, onratr-sigasi commented on step_2_sv.sv
> +//      Close the *Preprocessor View* and open the file step_3_find_references.vhd
Done

2023-07-19 18:18 UTC, onratr-sigasi commented on step_6_libraries.vhd
> +	--		file in another library.
Done.

2023-07-19 18:19 UTC, onratr-sigasi commented on step_5_warnings.vhd
> +--      Open the file step_6_libraries.vhd
Done.

2023-07-19 18:22 UTC, onratr-sigasi commented on step_6_libraries.vhd
> +--      Sigasi Studio fully supports VHDL's library mechanism. For that it needs
Done.

2023-07-19 18:22 UTC, onratr-sigasi commented on step_6_libraries.vhd
>  --      results in an unknown entity in the `clock_inst` instantiation.
Done.

2023-07-19 18:23 UTC, onratr-sigasi commented on step_6_libraries.vhd
> +	--      **F12** or **Ctrl+Left Click** it. This takes you to
Done.

2023-07-19 18:23 UTC, onratr-sigasi commented on my_lib/clock_generator.vhd
> +--      Open the file cmd_fsm.v in the vlog folder.
Done.

2023-07-19 18:25 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	//		`stage4` is missing from the port list.
Done.

2023-07-19 18:26 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	output stage4;
Done.

2023-07-19 18:27 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	//		`stage4` is missing from the port list.
Done.

2023-07-19 18:27 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	// 	    In the pop-up, click "Quick Fix" and "suppress" the warning message.
Done.

2023-07-19 18:28 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	//		";" is missing from the end of the assign statement.
Done.

2023-07-19 18:28 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +		//      Default clause is missing from the case statement. Sigasi knows this and
Done.

2023-07-19 18:31 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +		//		Also notice that a new warning message appears in the next line.
First warning was on line 89 and the second was is on line 90 (next line). It was at the end of the state machine but we moved up to show the user how a warning message is emerged.

2023-07-19 18:33 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +//      Open the file cmd_gen.v in the 'vlog' folder.
Done.

2023-07-19 18:34 UTC, onratr-sigasi commented on vlog/cmd_gen.v
> +    //      Notice that two components are instantiated here in this Verilog file.
We want to emphasize that a VHDL file is instantiated in a Verilog file.

2023-07-19 18:38 UTC, onratr-sigasi commented on vlog/cmd_gen.v
> +    //      **F12** or **Ctrl+Left Click** it. This takes you to the
Done.

2023-07-19 18:41 UTC, onratr-sigasi commented on vhdl/cnt_ena_ctrl.vhd
> +--      Open the file testbench.sv in the 'tb' folder.
Done.

2023-07-19 18:41 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      Observe that the port name of "clk" is also changed in the cmd_gen.v.
Done.

2023-07-19 18:46 UTC, onratr-sigasi commented on tb/testbench.sv
> +    //      This is because of the specific kind of port mapping in line 73, where
Could be better if we replace the physical reference with something else but I couldn't find anything else.

2023-07-19 18:47 UTC, onratr-sigasi commented on tb/testbench.sv
> +	//      Sigasi can help you search through your projects. To find out
Done.

2023-07-19 18:47 UTC, onratr-sigasi commented on tb/testbench.sv
> +//      Open the file final_step_reporting_issues.vhd
Done.

2023-07-19 19:05 UTC, onratr-sigasi commented on final_step_reporting_issues.vhd
>  --
Done a bit differently.

2023-07-19 19:06 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +		// 		Uncomment the line where the "default clause" is and notice how
Done.

2023-07-19 19:13 UTC, onratr-sigasi commented on step_1_welcome.vhd
>  --       These should be checked into your version control system.
Done.

2023-07-19 19:13 UTC, onratr-sigasi commented on step_1_welcome.vhd
>  --       When you change project or folder settings these will be saved in
Done.

2023-07-19 20:27 UTC, onratr-sigasi commented on step_1_welcome.vhd
>  --      behind the "ri" press **Ctrl+Space** and select "rising_edge".
Yes, but they are for different things. I think it's good if the users practice a bit.

2023-07-19 20:55 UTC, onratr-sigasi commented on step_1_welcome.vhd
>  ------------------------------------------------------------------------------------
Done.

2023-07-19 21:20 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--       files are missing. They will be added as you follow the steps.
Done.

2023-07-19 21:22 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--       Note that, in this project, **.project** and **.library_mapping.xml**
Done.

2023-07-19 21:23 UTC, onratr-sigasi commented on step_1_welcome.vhd
>  --      **Shift+Alt+F**.
Done. We have to make sure of the keybindings. It shows Ctrl+Shift+F in VS Code.

2023-07-20 09:37 UTC, tivervac requested changes

2023-07-20 09:37 UTC, tivervac commented on step_1_welcome.vhd
> +--      poped-up messages are warning you about language support being disabled.
```suggestion
--      pop-up messages are warning you about language support being disabled.  
```

2023-07-20 09:37 UTC, tivervac commented on step_2_sv.sv
> +//      "Sigasi: Add Verilog/SystemVerilog Support" and select it from the list
We already did this in step 1 now right?

2023-07-20 09:37 UTC, tivervac commented on step_2_sv.sv
> +//      "step_3_find_references.vhd"
```suggestion
//      "step_3_find_references.vhd".  
```

2023-07-20 09:37 UTC, tivervac commented on step_2_sv.sv
>  // TODO "Adjust validation settings"
There's an inconsistency in the casing for TODOs e.g. in this file you have `Adjust validation settings` and `Next Step` it should either be (`Adjust Validation Settings` and `Next Step`) or (`Adjust validation settings` and `Next step`). Be sure to apply your style of choice over all the files

2023-07-20 09:37 UTC, tivervac commented on step_3_find_references.vhd
> +--      Open the file "step_4_editor_features.vhd" using the *References View*
```suggestion
--      Open the file "step_4_editor_features.vhd" using the *References View*.  
```

2023-07-20 09:37 UTC, tivervac commented on vlog/cmd_fsm.v
> +//      Insert the missing ";" and note how the Error Marker disappears.
```suggestion
//      Insert the missing ";" and note how the Error Marker disappears.  
```

2023-07-20 09:37 UTC, tivervac commented on vlog/cmd_fsm.v
> +	      	endcase
Still loads of mixed indentation in this file

2023-07-26 06:01 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--      poped-up messages are warning you about language support being disabled.
Done.

2023-07-26 06:01 UTC, onratr-sigasi commented on step_2_sv.sv
> +//      "Sigasi: Add Verilog/SystemVerilog Support" and select it from the list
It was a left-over from the previous version. Removed.

2023-07-26 06:02 UTC, onratr-sigasi commented on step_2_sv.sv
> +//      "step_3_find_references.vhd"
Done.

2023-07-26 06:02 UTC, onratr-sigasi commented on step_2_sv.sv
>  // TODO "Adjust validation settings"
Done.

2023-07-26 06:02 UTC, onratr-sigasi commented on step_3_find_references.vhd
> +--      Open the file "step_4_editor_features.vhd" using the *References View*
Done.

2023-07-26 06:02 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +//      Insert the missing ";" and note how the Error Marker disappears.
Done.

2023-07-26 06:02 UTC, onratr-sigasi commented on vlog/cmd_fsm.v
> +	      	endcase
Done.

2023-07-26 14:48 UTC, tivervac reviewed
Looks mostly good now. I've also pushed some proofreading and whitespace changes. Feel free to revert or edit those if you disagree

2023-07-26 14:48 UTC, tivervac commented on step_1_welcome.vhd
> +--------------------------------------------------------------------------------
You mention to change the library, but then say that we should change the VHDL version.

I think it's better to remove this and say that this is Sigasi's replacement for the `Explorer`. Later on in the project you can use it to set the library or change severity of validations

```suggestion
--      project. To change the library of a file or folder, open the *Preference
--      View* and set your VHDL version by right-clicking the project name.
--------------------------------------------------------------------------------
```

2023-07-27 20:26 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--------------------------------------------------------------------------------
Done.

2023-08-01 15:19 UTC, tivervac approved these changes

2023-08-01 15:19 UTC, tivervac commented on step_1_welcome.vhd
> +--       match an editor of your choice such as Eclipse, IntelliJ IDEA or Vim.
```suggestion
-- NOTE: You can download extensions that change the keybindings of VS Code to
--       match an editor of your choice such as Eclipse, IntelliJ IDEA, or Vim.
```

2023-08-01 15:21 UTC, tivervac commented on step_1_welcome.vhd
> +--      or change severity of validations by right-clicking and selecting the
```suggestion
--      or change the severity of validations by right-clicking and selecting the 
```

2023-08-04 11:52 UTC, bartbrosens commented on step_1_welcome.vhd
> +--      or change severity of validations by right-clicking and selecting the
I would still add here that the Project View shows virtual and linked folders

2023-08-04 14:01 UTC, bartbrosens approved these changes

2023-08-07 07:14 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--       match an editor of your choice such as Eclipse, IntelliJ IDEA or Vim.
Done.

2023-08-07 07:14 UTC, onratr-sigasi commented on step_1_welcome.vhd
> +--      or change severity of validations by right-clicking and selecting the
Both done.

2023-08-09 11:49 UTC, merged